"plugins
call plug#begin('/home/myles/.vim/plugged')
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
Plug 'preservim/nerdtree'
Plug 'vifm/vifm.vim'
call plug#end()
let g:Hexokinase_highlighters = [ 'virtual' ]


set background=dark
set number
set cursorline
set termguicolors
colo darkspace
set expandtab
set tabstop=4
set shiftwidth=4
filetype plugin on
syntax on

"auto commands
autocmd vimenter * NERDTree

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif


nmap <silent> <TAB> :wincmd l<CR>

nmap <silent> <A-Up> :wincmd k<CR>

nmap <silent> <A-Down> :wincmd j<CR>

nmap <silent> <A-Left> :wincmd h<CR>

nmap <silent> <A-Right> :wincmd l<CR>

noremap ; l
noremap l j
noremap k k
noremap j h

nmap <silent> <n>
